---
id: omotesandorb-49
base_name: slide
tags: []
presentation_date: 
version: 1.0.0
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: 
  email: 
  rubygems_user: 
  slideshare_user: 
  speaker_deck_user: 
